"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """$character """
right_format = """
$git_branch
$git_state
$nodejs
$python
"""
# $git_status

[character]
format = """$symbol"""
success_symbol = '[âœ—](bold green)'
error_symbol = '[âœ—](bold red)'

[git_branch]
symbol = 'î‚ '
format = """[$symbol]($style)"""

[git_state]
format = """ [$state]($style)"""

[git_status]
format = """[$all_status]($style)"""

[nodejs]
symbol = 'îœ˜'
format = """[$symbol]($style)"""
detect_extensions = []

[python]
symbol = 'ğŸ'
format = """[$symbol]($style)"""
detect_extensions = []
detect_files = []
